### PR TITLE
New sample tab-mgt-person-csharp

### PR DESCRIPTION
**Pull request by mmsharepoint**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no   |
| New feature?    | no      |
| New sample?     | yes   |
| Related issues? |   |

## What's in this Pull Request?

This new sample is the Teams Toolkit with Visual Studio 2022 pendant to existing tab-mgt-person yo teams sample.
It uses the Teams MSAL2 provider of Microsoft Graph Toolkit to then show some MGT components.
I related both samples to each other in their README

### CODE REVIEW

**Comment by BobGerman** [comment]
Alas still having issues - 403's on the internal service and 401's on Graph.
Can we maybe do a screen share some time next week? Thanks!

**Comment by mmsharepoint** [comment]
Yes, we can try this together. I tested several times with user and admin consent and just wrote a blog post about removing user consented permissions as a side effect

**Comment by mmsharepoint** [comment]
> Alas still having issues - 403's on the internal service and 401's on Graph. Can we maybe do a screen share some time next week? Thanks!

Thanks for the session today @BobGerman I think we both moved forward a lot. I incorporated inconsistencies in the README as well as simplifying and fixing the deployment. Should work smooth now

**Comment by BobGerman** [comment]
Great sample - thanks!

**Pull request merged**
