### PR TITLE
bot-graph-bookmark sample added

### PR DESCRIPTION
**Pull request by ejazhussain**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

This is a sample Bookmark bot for Microsoft Teams. It allows a user in Teams to create bookmark item in the SharePoint list using Microsoft Graph API. It also implements single sign-on authentication.

### CODE REVIEW

**Comment by BobGerman** [comment]
Hi @ejazhussain - I have to apologize, Microsoft Build has taken all my time in the last couple of weeks so I haven't had a chance to try this update yet. I will try it next week when I get home; thanks for your patience and for contributing to Teams Dev Samples!

**Comment by ejazhussain** [comment]
> Hi @ejazhussain - I have to apologize, Microsoft Build has taken all my time in the last couple of weeks so I haven't had a chance to try this update yet. I will try it next week when I get home; thanks for your patience and for contributing to Teams Dev Samples!

No problem at all. Thank you for your message. Looking forward to submitting one more pull request in a couple of days.

**Comment by BobGerman** [comment]
Thanks for the sample - I fixed the following issues before approving:

1. Teams Toolkit no longer supports node v14 - removed that in readme
2. The code failed trying to write a "comments" field; changed instructions to match code, the field should be "BookmarkComments"
3. It was necessary to run `npm install` before running the app; added that to instructions
4. It's not possible to add to .env.local since it doesn't exist. Added instructions to build the app once (it will fail looking for the SP vars but it will create .env.local) - THEN to add the SP vars, and then to run it again
5. Added instructions to expect to log into the bot and consent to permissions
6. Fixed telemetry link

I do appreciate the sample but encourage you to clone your own repo and run it in a new folder before submitting to ensure all the instruction steps are included. Thanks!

**Comment by ejazhussain** [comment]
I appreciate your feedback and will make sure to adhere to the guidelines you mentioned before submitting my next sample. Thank you for taking the time to address the issues.”

**Comment by VesaJuvonen** [comment]
also @ejazhussain  - we'd love to get this demoed in one upcoming community calls - if you are up for it, please submit the following form and we'll get back to you on agreeing the exact time based on your availability - https://aka.ms/community/request/demo

Looking forward 👏🚀

**Comment by ejazhussain** [comment]
> 

@VesaJuvonen Thanks for reaching out. I would be delighted to present a demo during one of the community calls. I have already submitted my request.”

**Pull request merged**
