### PR TITLE
Added app-msteams-quiz-bot sample

### PR DESCRIPTION
**Pull request by marcel-paalvast**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                              |
| New sample?     | yes                               |
| Related issues? | NA |

## What's in this Pull Request?

Contains a new sample featuring a Microsoft Teams Quiz Bot capable of generating random questions using ChatGpt based on a user specified topic and language. Capable of running serverless in Azure using a Functions App as api and a Cosmos Database to maintain its state.

[Participated](https://github.com/microsoft/hack-together-teams/issues/89) in the [Microsoft Hack Together Teams](https://github.com/microsoft/hack-together-teams)

### CODE REVIEW

**Comment by rabwill** [comment]
Nice one @marcel-paalvast, thanks again for your contribution <3 . There is a small variable typo I found here: https://github.com/marcel-paalvast/teams-dev-samples/blob/ec335c886c8c5c7dfe30b6fa0cb4664df08dced4/samples/app-msteams-quiz-bot/MsTeamsQuizBot/Startup.cs#L33C4-L33C4 
Variable should be `config` to match the rest of the code to retrieve settings value or vice-versa.

I have fixed it in the commit where I pushed the telemetry link (new one) and a template for search for the adoption site.

@BobGerman the app works as expected using local set up.

**Comment by marcel-paalvast** [comment]
Thanks @rabwill . I removed the twitter url's added in 0b969f5 as it's not my twitter account and I don't have one to replace it with.

**Comment by rabwill** [comment]
Ohh @marcel-paalvast thank you for removing the twitter one. Apologies for assuming it's urs.

**Comment by BobGerman** [comment]
Great sample thanks so much @marcel-paalvast and thanks for testing it @rabwill !!
I renamed the folder to conform w/the naming convention -- "app-" is for apps that have multiple Teams capabilities such as a bot plus a message extension. So I made it "bot-msteams-quiz-bot" to make a minimal change and allow people looking for a bot to more easily find it.

**Pull request merged**
