### PR TITLE
Added new sample bot-teams-incidentmanagement

### PR DESCRIPTION
**Pull request by nanddeepn**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

MS Teams Incident Management Bot. This sample illustrates `sequential workflow`, `user specific views`, and `upto date adaptive cards` bot. Teams Incident Management bot is a sample app for handling incidents in Microsoft Teams using Adaptive Cards.

### CODE REVIEW

**Comment by BobGerman** [comment]
Hi @nanddeepn - I'm looking at this and am a bit concerned that you have copied code in the Microsoft.Bot.AdaptiveCards project from https://github.com/sowrabh-msft/BotBuilder-Samples/blob/jeffders/ac2-sample/experimental/adaptive-cards-2/Microsoft.Bot.Extensions/AdaptiveCards/AdaptiveCardAction.cs and **removed the copyright notices.** I need to check but that doesn't seem OK. Is there a way you can do this without re-releasing Microsoft code? If not, I can look into the process for doing this ... why did you remove the copyright notices?

Thanks

**Comment by nanddeepn** [comment]
Hello @BobGerman 
Thank you for noticing. 

The code reference is from [https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-teams-catering/csharp/Microsoft.Bot.AdaptiveCards/AdaptiveCardAction.cs](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-teams-catering/csharp/Microsoft.Bot.AdaptiveCards/AdaptiveCardAction.cs)

image

This code reference is coming from official docs.microsoft.com [Sequential Workflows](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/sequential-workflows) documentation of "Teams catering bot" under "Code sample" section.
image


I have mentioned Reference of [Sequential Workflows](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/sequential-workflows) page under `References` section in my [README.md](https://github.com/pnp/teams-dev-samples/blob/52dd4cdc41b1f7497e536fe5196eb6c366390c64/samples/bot-teams-incidentmanagement/README.md)

Thank you.

**Comment by BobGerman** [comment]
Got it - thanks!

**Comment by nanddeepn** [comment]
Thank you @BobGerman 
Please let me know for any code changes for this.

**Comment by BobGerman** [comment]
It's fine as it is - thanks for the sample!

**Pull request merged**
