### PR TITLE
Hacktogether live patient review

### PR DESCRIPTION
**Pull request by rfjschouten**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no

## What's in this Pull Request?

PR contains the 'Live patient review' Teams App which was created during the Microsoft Global Teams hack: hacktogether. This solution was the Grand Price Winner.

### CODE REVIEW

**Comment by rabwill** [comment]
Hi @rfjschouten thanks for the contribution here. I am reviewing the sample and everything look good except when I try to load an image file as shown in your demo, I get below error. Other features like feedback, add/delete patients etc work but I just could not load any image to play with it. What could be missing?

image

**Comment by rfjschouten** [comment]
> Hi @rfjschouten thanks for the contribution here. I am reviewing the sample and everything look good except when I try to load an image file as shown in your demo, I get below error. Other features like feedback, add/delete patients etc work but I just could not load any image to play with it. What could be missing?
> 
> image

Hi @rabwill, there is nothing missing. No extra steps necessary for the image upload. I have seen this error while debugging through f5 earlier too. I haven't been able to pin point what the exact reason is for this error. What I have seen, is when you debug multiple times and use the same meeting again, the Tab is added multiple times. It looks like this is causing these kind of errors. What helps is setting up a new meeting and debug into this meeting. I have also deployed it on our own demo environment and this issue is never coming up again. Could you try and see if it works when you debug and use a 'clean' calendar event?

**Comment by rabwill** [comment]
Sure @rfjschouten thanks for the tip! It will try it. I created a new meeting however but may be there were other instances like you mentioned.

**Comment by rabwill** [comment]
Just tested the app after deploying and it works really well. Something to look into with the F5 /local debug experience of app using these SDKs. Thanks Robert. Really great app :) Will be merged soon.
@BobGerman , reviewed and the app works as expected with an issue, mainly a feedback for product. We can discuss.

**Comment by rabwill** [comment]
@BobGerman all yours to merge!

**Comment by BobGerman** [comment]
This is great - thanks so much @rfjschouten for the sample and thanks @rabwill for your help in testing!

**Pull request merged**
