### PR TITLE
Document Review SPFx Messaging Extension

### PR DESCRIPTION
**Pull request by mmsharepoint**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                              |
| New sample?     | yes                             |
| Related issues? |  |

## What's in this Pull Request?
This is my 3rd example on a doc review Teams Messaging extension (like #18 and #21)
This time it uses SPFx technology in the frontend for the task modules

### CODE REVIEW

**Comment by BobGerman** [comment]
This looks awesome Markus! Thanks for submitting!

Can you please provide the package.json file?
Also please fix the broken image references in the Readme.md file.

I look forward to getting this out there, this is the very 1st SPFx messaging extension sample I'm aware of!

**Comment by mmsharepoint** [comment]
Hi Bob,
the package.json file(s) are there:
Take into consideration this sample contains "two" solutions:

1. A **webpart** solution (in the corresponding "webpart" folder) containing two webpart components
2. A small **bot** solution (in the corresponding "bot" folder)  containing a small bot

I can fix the broken links in the README (case-sensitive file names, once again ... my typical redme error :-( ) PLUS I maybe should point the above fact out so a consumer indeed needs to run npm install twice (inside both solution folders) ...
Best
Markus

**Comment by mmsharepoint** [comment]
@BobGerman I think it should be fine now? Or did I miss anything?

**Comment by BobGerman** [comment]
Not sure how I missed that - it's the only way you could do it! Nice sample, thanks!

**Pull request merged**
