### PR TITLE
Commiting the sample Coorporate Helper - Issue #123 In hack-together-…

### PR DESCRIPTION
**Pull request by fsdp15**
…teams - felipedotti@microsoft.com - Commiting to teams-dev-samples for PR

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               | 
| New feature?    | no                             | 
| New sample?     | yes                              | 
| Related issues? | #123 (Teams Hackathon repository) |

## What's in this Pull Request?

> This PR is adding the app CoorporateHelper from the Teams Hackathon into the Teams Dev Samples Repository. Issue 123 in Teams hackathon Repository.

### CODE REVIEW

**Comment by fsdp15** [comment]
Cannot seems to able to add the label teams global hack.

**Comment by BobGerman** [comment]
Hi Felipe - this looks great but I'm having a bit of trouble running the app.
I am testing on a clean Windows 10 machine w/VS 2022.
The app builds fine but the browser opens and shows this error:

Error 500.31 - Failed to load ASP.NET Core runtime
Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.
Specific error detected by ANCM:
You must install or update .NET to run this application. App: C:\Users\Bob\teams-dev-samples-felipedotti\samples\app-coorporatehelper-tab\bin\Debug\netcoreapp3.1\CoorporateHelper.dll Architecture: x64 Framework: 'Microsoft.AspNetCore.App', version '3.1.0' (x64) .NET location: C:\Program Files\dotnet\ The following frameworks were found: 6.0.16 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] 7.0.5 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] Learn about framework resolution: https://aka.ms/dotnet/app-launch-failed To install missing framework, download: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526

I tried installing the missing (old) 3.1 framework but I still encounter the same error. Can you help?

**Comment by BobGerman** [comment]
ALSO I added a .gitignore file to the project folder so build artifacts won't be persisted to Github.

ALSO I made a couple small changes to the README.md file - clarified the need to enable the scope for each client application as it's added, and removed the note about the "Teams channel" - this is not a bot is it?

 -

**Comment by BobGerman** [comment]
If this is just a tab please rename the sample to begin with "tab-" as in "tab-corporatehelper".

Also not to be picky but it's spelled "corporate " not "coorporate" - since the typo is in the folder name I stumbled trying to go there in the command line as I typed "corp<tab>" and it didn't complete due to the extra "o". It would be easier for users if this was fixed as well.

Thanks!

**Comment by fsdp15** [comment]
Hi @BobGerman,

Thanks for the info, updates, and corrections. I will take a look at the .NET error.

**Comment by fsdp15** [comment]
Hey @BobGerman , I have tried to run the app in a fresh Windows 10 and got the same error as you.

I solved this by doing below:

Install .NET 7.0: https://dotnet.microsoft.com/en-us/download
Install .NET Core 3.1 Runtime (v3.1.32): https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-3.1.32-windows-x64-installer

It seems I used some dependency that requires this v3.1.32 old version. Is this ok?

I have updated the readme.md to include these two prerequisites (previously it was pointing to dotnet 6.0).

I have also fixed the filenames and typos.

Could you please check it again?

Thanks.

**Pull request merged**
