### PR TITLE
New Sample: Tenant Health and Announcements in Copilot

### PR DESCRIPTION
**Pull request by pkbullock**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     |  yes                               |
| Related issues? | N/A  |

## What's in this Pull Request?

- All the code, setup and docs - some of the setup was manual at this point most likely looking to improve the sample over time. Especially if MS change Copilot significantly.

Please let me know if you need anything more - totally happy with suggestions, improvements, anything really, all feedback is good learning.  I may improve the screenshot for the output with a Gif to show the output in action.

### CODE REVIEW

**Comment by pkbullock** [comment]
Converting to draft as I am making changes to the sample to improve upon it.

**Comment by pkbullock** [comment]
- Added new feature to follow a health issue (or at least call an Az Function to register to follow an issue) - process not added thereon to action the follow but does demonstrate the "act" part of the message extension within Copilot]
- Added Video/Gif of the Copilot example to show operation
- Tweaks setup docs accordingly.

**Comment by pkbullock** [comment]
Ready for submission now.

**Comment by BobGerman** [comment]
Nice one -- thanks!

**Pull request merged**
