### PR TITLE
ME action and search with SP

### PR DESCRIPTION
**Pull request by VaraPrasad-MSFT**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no - yes?                               |
| New feature?    | no - yes?                               |
| New sample?     | no - yes?                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by BobGerman** [comment]
Hi @VaraPrasad-MSFT - this looks like a great sample, thanks for submitting!
I made some changes to the readme - we require an image at the front, so I added that, and I wrote a paragraph explaining a little more what the app does. Did I get that right? Is it OK or do you prefer something else?
Also I added a .gitignore and removed some files in the obj folder that had been checked in accidentally.

If this is all Ok then I will approve, else let me know or make additional changes in the branch. Thanks!

PS: Would you be willing/interested in demonstrating this in one of the community calls, like the Teams Dev Community?
Thanks!

**Comment by VaraPrasad-MSFT** [comment]
> Hi @VaraPrasad-MSFT - this looks like a great sample, thanks for submitting!
> I made some changes to the readme - we require an image at the front, so I added that, and I wrote a paragraph explaining a little more what the app does. Did I get that right? Is it OK or do you prefer something else?
> Also I added a .gitignore and removed some files in the obj folder that had been checked in accidentally.
> 
> If this is all Ok then I will approve, else let me know or make additional changes in the branch. Thanks!
> 
> PS: Would you be willing/interested in demonstrating this in one of the community calls, like the Teams Dev Community?
> Thanks!

Thanks @BobGerman ,

I will push few changes tomorrow which i received as feedback comment from Adaptive card team, and update in the PR. We can push the changes at shot.

**Comment by arun-msft** [comment]
Thanks for the feedback @BobGerman. This is also from my team. I will do those changes and will get back to you.

**Comment by BobGerman** [comment]
Thanks; the updates to the documentation look good!
However somehow you removed the .gitignore I created, made a new incomplete one at the root of the samples repo, re-introduced temp and object files that should never be checked in, and removed the telemetry link (image at the end of the README). So I re-did all those changes and am now accepting the PR.

I really do appreciate your sharing but please be mindful of these issues going forward; they are explained in the contribution guidelines here: https://github.com/pnp/teams-dev-samples/blob/master/.github/CONTRIBUTING.md#3-gitignore (sections 3 and 6).

Thanks!

**Pull request merged**
