### PR TITLE
Tab spfx oauth2

### PR DESCRIPTION
**Pull request by AhmadiRamin**
Sample on how to implement OAuth 2.0 flow using the Microsoft Teams SKD and SharePoint Framework.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks @AhmadiRamin, it looks great. 

Your PR seems to touch a few more files outside of your sample though. Is it possible that you forked this repository a while ago and your fork was out of sync?

If that's the case, I'd recommend refreshing your fork first and re-adding your cool sample.

**Comment by AhmadiRamin** [comment]
Hi @hugoabernier, I forked the repository before adding my sample, I will try to fork it again, do I need to remove this one?

**Comment by AhmadiRamin** [comment]
Maybe that's because I created a pull request to merge to Dev branch? should we merged back to Dev or Master?

**Comment by hugoabernier** [comment]
> Maybe that's because I created a pull request to merge to Dev branch? should we merged back to Dev or Master?

I just noticed that too. I'll defer to @BobGerman and see how he wishes to proceed.

**Comment by BobGerman** [comment]
Hi @AhmadiRamin - First this is a great sample! I didn't have missing files, was that resolved?

Anyway I apologize since I didn't have the Teams README templates when you submitted; I'm just getting started here. I'd like you to please fill in the new README.md. The template for SPFx tabs is here: https://github.com/pnp/teams-dev-samples/tree/master/samples/_SAMPLE_templates/spfx-sample

Also please include full build instructions in the readme or somewhere in your sample folder. I'm happy to have a link to your blog as well, but we always try to make the samples self-contained so everything is right there. Blogs sometimes move over time, so it's important that every sample has the essential info to make it work right in the repo.

Finally, I think you're underselling this ... it's way more than an OAuth sample, it also shows how to integrate with Box! You should take a victory lap! I'd suggest you update the title and description to explain the Box integration _and_ that this can be used as a general case for other OAuth based services.

Does that make sense? Thanks!

**Comment by AhmadiRamin** [comment]
Hi @BobGerman, sorry I should have waited until the template is available, but I'm happy to update the README.
Thanks for your notes and I will take them into consideration while adding more details to the README :)

**Comment by AhmadiRamin** [comment]
@BobGerman  I updated the README.md.

**Comment by BobGerman** [comment]
Hi @AhmadiRamin - Thanks for switching to the template. The setup instructions in your readme seem incomplete however ... you create 2 pages and they will run in SharePoint... are you supposed to copy the pages from the /pages folder in your project? And once you put them somewhere, where do you reference them, you must need to put those pages' URL's somewhere? And then how do you build the project? How do you deploy it to Teams?

Please complete the install instructions ... thanks!

**Comment by AhmadiRamin** [comment]
Hi @BobGerman , I'm so sorry I completely forget to update the instructions due to being busy at work, is it ok to create a new PR for that? I will be more than happy to demo it as well.

**Comment by BobGerman** [comment]
Hi @AhmadiRamin - 
This is a great sample; would you be interested in demonstrating this on an upcoming Teams community call?
I'd love to include it on the October 20, 2020 call (11-12 Eastern time); if you're willing you would have 10-15 minutes to demonstrate and explain your sample. Are you interested?
Thanks!

**Pull request merged**
