### PR TITLE
New sample tab-office-offer-creation

### PR DESCRIPTION
**Pull request by mmsharepoint**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no|
| New feature?    | no  |
| New sample?     |   yes |
| Related issues? |  |

## What's in this Pull Request?

This sample contains a tab and a search-based messaging extension. Both able to act as Microsoft 365 across apps.
The tab is able to create SharePoint template-based and content-type based offer documents,
while the search-based messaging extension allows to send the documents for review/publish as Adaptive Cards via Teams AND Outlook.
See screenshots in assets folder and linked Blog series for further illustration.

### CODE REVIEW

**Comment by BobGerman** [comment]
Hi @mmsharepoint - with apologies for waiting till the day before the community call to check this sample -

I was unable to build the sample as instructed.
Specifically, 'gulp manifest' returns this error:

[10:47:45] Error in plugin "validateSchemas"
Message:
    manifest.json: No enum match for: groupchat
Details:
    domainEmitter: [object Object]
    domainThrown: false

**Comment by mmsharepoint** [comment]
Fixed groupChat (capital C necessary)
Sorry for that, didn't use the manifest for a while. Same error was in my personal repo

**Comment by BobGerman** [comment]
Haha so did I (I did at least look for a solution!)
I'll try to get it done for tomorrow's call then; thanks!

**Comment by BobGerman** [comment]
Great sample - thanks @mmsharepoint !!

**Pull request merged**
