### PR TITLE
New sample msgext-action-search-data-node

### PR DESCRIPTION
**Pull request by mmsharepoint**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no   |
| New feature?    | no  |
| New sample?     |  yes|
| Related issues? |   |

## What's in this Pull Request?

It's more or less the TTK version for VSCode of msgext-action-search-data 
(which is already there and was presented but realized with Visual Studio 2022 C#)

### CODE REVIEW

**Comment by BobGerman** [comment]
Great idea and it looks good
However I got an error when I ran it. Are there missing setup steps? Or do you need to provision Azurite or something?

[2024-06-19T23:26:45.121Z] [Error] - code:fileCreateOrUpdateEnvironmentFile.MissingEnvironmentVariablesError, message: The program cannot proceed as the following environment variables are missing: 'AZURE_TABLE_ACCOUNTNAME,AZURE_TABLE_KEY', which are required for file: c:\source\PR\teams-dev-samples\samples\msgext-action-search-data-node\teamsapp.local.yml. Make sure the required variables are set either by editing the .env file 'c:\source\PR\teams-dev-samples\samples\msgext-action-search-data-node\env\.env.local' with the correct names and values , or by setting the system environment variables with the correct names and values. If you are developing with a new project created with Teams Toolkit, running provision or debug will register correct values for these environment variables.
 Help link: https://aka.ms/teamsfx-v5.0-guide#environments

**Comment by mmsharepoint** [comment]
> Great idea and it looks good However I got an error when I ran it. Are there missing setup steps? Or do you need to provision Azurite or something?
> 
> [2024-06-19T23:26:45.121Z] [Error] - code:fileCreateOrUpdateEnvironmentFile.MissingEnvironmentVariablesError, message: The program cannot proceed as the following environment variables are missing: 'AZURE_TABLE_ACCOUNTNAME,AZURE_TABLE_KEY', which are required for file: c:\source\PR\teams-dev-samples\samples\msgext-action-search-data-node\teamsapp.local.yml. Make sure the required variables are set either by editing the .env file 'c:\source\PR\teams-dev-samples\samples\msgext-action-search-data-node\env.env.local' with the correct names and values , or by setting the system environment variables with the correct names and values. If you are developing with a new project created with Teams Toolkit, running provision or debug will register correct values for these environment variables. Help link: https://aka.ms/teamsfx-v5.0-guide#environments

You are totally right, Bob. Forgot to mention the necessity of an Azure Table and where to configure and how to fill it

**Comment by rabwill** [comment]
Hi @mmsharepoint Markus ,

Nice work as usual! Few small issues I faced to get the F5 work seamlessly are mentioned below.  If we can address these, then the sample would super smooth for folks to try and good to be merged @BobGerman .

- Dev dependencies missing 
```
npm i --save-dev @azure/data-tables
npm i --save-dev @azure/functions
npm i --save-dev @types/node
```
- Instructions for Azure set up could be improved. 
AZURE_TABLE_ACCOUNTNAME should be the name of the **storage account** where azure table is to be created.
AZURE_TABLE_KEY is actually the **storage acc access key**. 
Names could be improved for easy configuration.

A step is missing where the user will have to create the table in the above storage account with name `Products2` as defined in *azService.ts* file.

**Comment by mmsharepoint** [comment]
> Hi @mmsharepoint Markus ,
> 
> Nice work as usual! Few small issues I faced to get the F5 work seamlessly are mentioned below. If we can address these, then the sample would super smooth for folks to try and good to be merged @BobGerman .
> 
> * Dev dependencies missing
> 
> ```
> npm i --save-dev @azure/data-tables
> npm i --save-dev @azure/functions
> npm i --save-dev @types/node
> ```
> 
> * Instructions for Azure set up could be improved.
>   AZURE_TABLE_ACCOUNTNAME should be the name of the **storage account** where azure table is to be created.
>   AZURE_TABLE_KEY is actually the **storage acc access key**.
>   Names could be improved for easy configuration.
> 
> A step is missing where the user will have to create the table in the above storage account with name `Products2` as defined in _azService.ts_ file.

Hi @rabwill Rabia,
I think I am done with the suggested and sense-making improvements

Markus

**Comment by BobGerman** [comment]
Cool sample - first action ME as a Copilot plugin!

**Pull request merged**
