### PR TITLE
feat: added sample msgext-openai-stock-price

### PR DESCRIPTION
**Pull request by anoopt**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | NA |

## What's in this Pull Request?

- This sample is a message extension for Microsoft Teams that provides information about the stock price of a company. 
- The information is based on the response from Finnhub. 
- The information exchanged between the user and the message extension is in natural language. 
- The message extension uses [OpenAI's function calling feature](https://openai.com/blog/function-calling-and-other-api-updates) to understand whether a function in the code needs to be called based on user's query. 
- The message extension calls OpenAI API which transforms the JSON reponse from [Finnhub API](https://finnhub.io/) to natural language.

### CODE REVIEW

**Comment by BobGerman** [comment]
Thanks for another great sample; would you like to present this on one of the Community calls?

**Comment by anoopt** [comment]
Thank you @BobGerman . Yes, would love to present these in a community call. 

Since both this sample and the other sample (TfL Status) are based on a similar concept, OpenAI function calling, do you think it is ok to present them in the same call?

**Comment by anoopt** [comment]
Also @BobGerman a quick one - looks like the site for the samples is not showing the samples submitted in the last 12 months - https://pnp.github.io/teams-dev-samples/.

`year+1` needed somewhere :D ?

**Comment by anoopt** [comment]
@BobGerman did you get a chance to see my previous message?

Also, a small favour please. The images for a couple of samples I submitted are not showing up on the solution gallery site. So if you don't mind can you please update the sample.json of this sample and *bot-openai-tfl-status*?

**Pull request merged**
